### ISSUE TITLE
Filter tasks by variables in Task Search not working 

### ISSUE THREAD

**Issue by AmmarMohamed21** [camunda-community-hub/camunda-tasklist-client-java#70]
Using Task List client to retrieve tasks and filtering by specific variables not working, the filter is not used and all tasks are retrieved
Version: 8.3.3.2

**Comment by chDame** [comment]
Hi @AmmarMohamed21,

Could you tell me what is your tasklist version (should be 8.3.3 at least) and could you write a peace of code that you tested and that is not working. This version as tested with some simple searches like this:
```
ts = new TaskSearch().addVariableFilter("riskLevels", List.of("yellow", "yellow")).addVariableFilter("age", 30);
TaskList tasksFromVariableSearch = client.getTasks(ts);
```

**Comment by AmmarMohamed21** [comment]
Version 8.3.3.2, 
I was testing and figured out few cases 

For Strings:

```
//This works
TaskSearch ts = new TaskSearch();
ts.addVariableFilter("id", "12345");
```

```
// This Doesn't work
TaskByVariables taskByVariable1 = new TaskByVariables();
taskByVariable1.setName("id");
taskByVariable1.setValue("12345");
List<TaskByVariables> taskByVariablesList = new ArrayList<>();
taskByVariablesList.add(taskByVariable1);
ts.setTaskVariables(taskByVariablesList);
```

```
// This Works for a String by adding \" \"
TaskByVariables taskByVariable1 = new TaskByVariables();
taskByVariable1.setName("id");
taskByVariable1.setValue("\"12345\"");
List<TaskByVariables> taskByVariablesList = new ArrayList<>();
taskByVariablesList.add(taskByVariable1);
ts.setTaskVariables(taskByVariablesList);
```

For booleans it didn't work in both cases
```
//Doesn't work
TaskSearch ts = new TaskSearch();
ts.addVariableFilter("isManager", true);
```

```
// Doesn't work
TaskByVariables taskByVariable1 = new TaskByVariables();
taskByVariable1.setName("isManager");
taskByVariable1.setValue("true");
List<TaskByVariables> taskByVariablesList = new ArrayList<>();
taskByVariablesList.add(taskByVariable1);
ts.setTaskVariables(taskByVariablesList);
```

**Comment by chDame** [comment]
Hi @AmmarMohamed21,

It's because the api awaits a value in JSON format. The addVariableFilter is doing that magic for you. But if you use the TaskByVariables generated from the API, you need to do the magic yourself. You can use the JsonUtils.toJsonString if you want to do so. Also if you use the TaskByVariables, you need to provide the operator. A full example is provided in the addVariableFilter : https://github.com/camunda-community-hub/camunda-tasklist-client-java/blob/fe09396a67375e309ad3f1090e1040bdca1abb02/src/main/java/io/camunda/tasklist/dto/TaskSearch.java#L130

For the boolean, I would assume the attribute to be named manager rather than isManager (looks like a method name). Are you sure that the variable is isManager and not manager ?

**Comment by AmmarMohamed21** [comment]
funny enough this was a typo in the variable name, it works as expected thanks
